############################################################################################
#    Song-level genre labels for MSD songs based on majority vote (or consensus for n=2).
#    Format: '#'  = comment
#            '\t' = field separator
#            '\n' = line separator
#    Fields: trackId, majority-genre, minority-genre?
############################################################################################
j1	Jazz
j2	Jazz
j3	Jazz
j4	Jazz
j5	Jazz
j6	Jazz
j7	Jazz
j8	Jazz
j9	Jazz
p1	Pop
p2	Pop
p3	Pop
p4	Pop
p5	Pop
p6	Pop
c1	Classic
c2	Classic
c3	Classic
c4	Classic
c5	Classic
c6	Classic
c7	Classic
c8	Classic
c9	Classic